### ISSUE TITLE
ERROR: Model Controller: Failed creating provence record

### ISSUE THREAD

**Issue by geoye** [manaakiwhenua/LUMASS#1]
Hello, I used this remarkable model accoring to the user guide, and I met some problem when it comes to the basic **"How to create a simple processing pipeline"**. It poped up an error and then crashed.
I ran the model step by step but failed. Then I ran your `Exercise1_SimplePipeline.lmx` file in the `SampleData/models` folder, changed the filename, and it still did not work.
Here is the screenshot of the error reporting:
![image](https://user-images.githubusercontent.com/62197564/132120853-663e51d3-9478-4635-a689-256ec4315634.png)
Can you give me some useful advice on how to fix this problem? Thank you so much!

**Comment by heralex** [comment]
Hi YonnyiYe, first of all apologies for my belated response - I actually did forget to watch this repo, so didn't pick-up on it ...
Anyway, I guess you're using LUMASS 0.9.59, right? While the model works and produces the expected output, the failure to produce a provenance record is a known issue with that version. However, the development of LUMASS has meanwhile progressed quite a bit, so I'd encourage you to try the updated version that doesn't show that issue. I'll upload a new windows release and Linux AppImage shortly.
